
package com.byd.wms.webservice.ewm.sap.rfc.functions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZRFC_WMS_003", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "http://10.9.44.14:8000/sap/bc/srt/wsdl/flv_10002A111AD1/bndg_url/sap/bc/srt/rfc/sap/zrfc_wms_003/200/zrfc_wms_003/zrfc_wms_003?sap-client=200")
public class ZRFCWMS003_Service
    extends Service
{

    private final static URL ZRFCWMS003_WSDL_LOCATION;
    private final static WebServiceException ZRFCWMS003_EXCEPTION;
    private final static QName ZRFCWMS003_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "ZRFC_WMS_003");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.9.44.14:8000/sap/bc/srt/wsdl/flv_10002A111AD1/bndg_url/sap/bc/srt/rfc/sap/zrfc_wms_003/200/zrfc_wms_003/zrfc_wms_003?sap-client=200");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZRFCWMS003_WSDL_LOCATION = url;
        ZRFCWMS003_EXCEPTION = e;
    }

    public ZRFCWMS003_Service() {
        super(__getWsdlLocation(), ZRFCWMS003_QNAME);
    }

    public ZRFCWMS003_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZRFCWMS003_QNAME, features);
    }

    public ZRFCWMS003_Service(URL wsdlLocation) {
        super(wsdlLocation, ZRFCWMS003_QNAME);
    }

    public ZRFCWMS003_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZRFCWMS003_QNAME, features);
    }

    public ZRFCWMS003_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZRFCWMS003_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZRFCWMS003
     */
    @WebEndpoint(name = "ZRFC_WMS_003")
    public ZRFCWMS003 getZRFCWMS003() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZRFC_WMS_003"), ZRFCWMS003.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZRFCWMS003
     */
    @WebEndpoint(name = "ZRFC_WMS_003")
    public ZRFCWMS003 getZRFCWMS003(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZRFC_WMS_003"), ZRFCWMS003.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZRFCWMS003_EXCEPTION!= null) {
            throw ZRFCWMS003_EXCEPTION;
        }
        return ZRFCWMS003_WSDL_LOCATION;
    }

}
