
package org.tempuri.liku;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "clsBYDService", targetNamespace = "http://liku.tempuri.org/", wsdlLocation = "http://10.23.1.39:8080/clsBYDService?wsdl")
public class ClsBYDService
    extends Service
{

    private final static URL CLSBYDSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLSBYDSERVICE_EXCEPTION;
    private final static QName CLSBYDSERVICE_QNAME = new QName("http://liku.tempuri.org/", "clsBYDService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.23.1.39:8080/clsBYDService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLSBYDSERVICE_WSDL_LOCATION = url;
        CLSBYDSERVICE_EXCEPTION = e;
    }

    public ClsBYDService() {
        super(__getWsdlLocation(), CLSBYDSERVICE_QNAME);
    }

    public ClsBYDService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLSBYDSERVICE_QNAME, features);
    }

    public ClsBYDService(URL wsdlLocation) {
        super(wsdlLocation, CLSBYDSERVICE_QNAME);
    }

    public ClsBYDService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLSBYDSERVICE_QNAME, features);
    }

    public ClsBYDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClsBYDService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBYDWMSInterface
     */
    @WebEndpoint(name = "BasicHttpBinding_IBYDWMSInterface")
    public IBYDWMSInterface getBasicHttpBindingIBYDWMSInterface() {
        return super.getPort(new QName("http://liku.tempuri.org/", "BasicHttpBinding_IBYDWMSInterface"), IBYDWMSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBYDWMSInterface
     */
    @WebEndpoint(name = "BasicHttpBinding_IBYDWMSInterface")
    public IBYDWMSInterface getBasicHttpBindingIBYDWMSInterface(WebServiceFeature... features) {
        return super.getPort(new QName("http://liku.tempuri.org/", "BasicHttpBinding_IBYDWMSInterface"), IBYDWMSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLSBYDSERVICE_EXCEPTION!= null) {
            throw CLSBYDSERVICE_EXCEPTION;
        }
        return CLSBYDSERVICE_WSDL_LOCATION;
    }

}
