
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS_WLMS_ToWMSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSWLMSToWMSSoap {


    /**
     * 总装物流根据需求收货、退货
     * 
     * @param param
     * @return
     *     returns byd.wms.modules.wsclient.wlms.WSWMSList
     */
    @WebMethod(operationName = "Add_DemandReceive", action = "http://tempuri.org/Add_DemandReceive")
    @WebResult(name = "Add_DemandReceiveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Add_DemandReceive", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.AddDemandReceive")
    @ResponseWrapper(localName = "Add_DemandReceiveResponse", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.AddDemandReceiveResponse")
    public WSWMSList addDemandReceive(
        @WebParam(name = "Param", targetNamespace = "http://tempuri.org/")
        WSWMSList param);

    /**
     * 配送单需求拆分、重新发布等操作
     * 
     * @param param
     * @return
     *     returns byd.wms.modules.wsclient.wlms.WSWMSDispatchingList
     */
    @WebMethod(operationName = "Add_DispatchingReceive", action = "http://tempuri.org/Add_DispatchingReceive")
    @WebResult(name = "Add_DispatchingReceiveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Add_DispatchingReceive", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.AddDispatchingReceive")
    @ResponseWrapper(localName = "Add_DispatchingReceiveResponse", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.AddDispatchingReceiveResponse")
    public WSWMSDispatchingList addDispatchingReceive(
        @WebParam(name = "Param", targetNamespace = "http://tempuri.org/")
        WSWMSDispatchingList param);

    /**
     * 获取拣配单头表信息
     * 
     * @param myPage
     * @param myHeader
     * @return
     *     returns byd.wms.modules.wsclient.wlms.WSWMSDispatching
     */
    @WebMethod(operationName = "Get_Dispatching_Header", action = "http://tempuri.org/Get_Dispatching_Header")
    @WebResult(name = "Get_Dispatching_HeaderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Dispatching_Header", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.GetDispatchingHeader")
    @ResponseWrapper(localName = "Get_Dispatching_HeaderResponse", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.GetDispatchingHeaderResponse")
    public WSWMSDispatching getDispatchingHeader(
        @WebParam(name = "myHeader", targetNamespace = "http://tempuri.org/")
        WSWMSDispatchingHeader myHeader,
        @WebParam(name = "myPage", targetNamespace = "http://tempuri.org/")
        WSWMSPage myPage);

    /**
     * 获取拣配单行项目表信息
     * 
     * @param myPage
     * @param myItem
     * @return
     *     returns byd.wms.modules.wsclient.wlms.WSWMSDispatching
     */
    @WebMethod(operationName = "Get_Dispatching_Item", action = "http://tempuri.org/Get_Dispatching_Item")
    @WebResult(name = "Get_Dispatching_ItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Dispatching_Item", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.GetDispatchingItem")
    @ResponseWrapper(localName = "Get_Dispatching_ItemResponse", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.GetDispatchingItemResponse")
    public WSWMSDispatching getDispatchingItem(
        @WebParam(name = "myItem", targetNamespace = "http://tempuri.org/")
        WSWMSDispatchingItem myItem,
        @WebParam(name = "myPage", targetNamespace = "http://tempuri.org/")
        WSWMSPage myPage);

    /**
     * 获取拣配单组件信息
     * 
     * @param myPage
     * @param myComponent
     * @return
     *     returns byd.wms.modules.wsclient.wlms.WSWMSDispatching
     */
    @WebMethod(operationName = "Get_Dispatching_Component", action = "http://tempuri.org/Get_Dispatching_Component")
    @WebResult(name = "Get_Dispatching_ComponentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Dispatching_Component", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.GetDispatchingComponent")
    @ResponseWrapper(localName = "Get_Dispatching_ComponentResponse", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.GetDispatchingComponentResponse")
    public WSWMSDispatching getDispatchingComponent(
        @WebParam(name = "myComponent", targetNamespace = "http://tempuri.org/")
        WSWMSDispatchingComponent myComponent,
        @WebParam(name = "myPage", targetNamespace = "http://tempuri.org/")
        WSWMSPage myPage);

    /**
     * 通过拣配单号获取拣配单信息
     * 
     * @param myHeader
     * @return
     *     returns byd.wms.modules.wsclient.wlms.WSWMSDispatching
     */
    @WebMethod(operationName = "Get_DispatchingByNo", action = "http://tempuri.org/Get_DispatchingByNo")
    @WebResult(name = "Get_DispatchingByNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_DispatchingByNo", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.GetDispatchingByNo")
    @ResponseWrapper(localName = "Get_DispatchingByNoResponse", targetNamespace = "http://tempuri.org/", className = "byd.wms.modules.wsclient.wlms.GetDispatchingByNoResponse")
    public WSWMSDispatching getDispatchingByNo(
        @WebParam(name = "myHeader", targetNamespace = "http://tempuri.org/")
        WSWMSDispatchingHeader myHeader);

}
