
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_WLMS_ToWMS", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.23.11.7/WLMS/WebService/WS_WLMS_ToWMS.asmx?wsdl")
public class WSWLMSToWMS
    extends Service
{

    private final static URL WSWLMSTOWMS_WSDL_LOCATION;
    private final static WebServiceException WSWLMSTOWMS_EXCEPTION;
    private final static QName WSWLMSTOWMS_QNAME = new QName("http://tempuri.org/", "WS_WLMS_ToWMS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.23.11.7/WLMS/WebService/WS_WLMS_ToWMS.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSWLMSTOWMS_WSDL_LOCATION = url;
        WSWLMSTOWMS_EXCEPTION = e;
    }

    public WSWLMSToWMS() {
        super(__getWsdlLocation(), WSWLMSTOWMS_QNAME);
    }

    public WSWLMSToWMS(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSWLMSTOWMS_QNAME, features);
    }

    public WSWLMSToWMS(URL wsdlLocation) {
        super(wsdlLocation, WSWLMSTOWMS_QNAME);
    }

    public WSWLMSToWMS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSWLMSTOWMS_QNAME, features);
    }

    public WSWLMSToWMS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSWLMSToWMS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSWLMSToWMSSoap
     */
    @WebEndpoint(name = "WS_WLMS_ToWMSSoap")
    public WSWLMSToWMSSoap getWSWLMSToWMSSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WS_WLMS_ToWMSSoap"), WSWLMSToWMSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSWLMSToWMSSoap
     */
    @WebEndpoint(name = "WS_WLMS_ToWMSSoap")
    public WSWLMSToWMSSoap getWSWLMSToWMSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WS_WLMS_ToWMSSoap"), WSWLMSToWMSSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WSWLMSToWMSSoap
     */
    @WebEndpoint(name = "WS_WLMS_ToWMSSoap12")
    public WSWLMSToWMSSoap getWSWLMSToWMSSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "WS_WLMS_ToWMSSoap12"), WSWLMSToWMSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSWLMSToWMSSoap
     */
    @WebEndpoint(name = "WS_WLMS_ToWMSSoap12")
    public WSWLMSToWMSSoap getWSWLMSToWMSSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WS_WLMS_ToWMSSoap12"), WSWLMSToWMSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSWLMSTOWMS_EXCEPTION!= null) {
            throw WSWLMSTOWMS_EXCEPTION;
        }
        return WSWLMSTOWMS_WSDL_LOCATION;
    }

}
